---
- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/vars.yml"

  tasks:
    - name: Сохранить пароль для расшифровки в файл
      ansible.builtin.copy:
        content: "{{ password }}"
        dest: "/tmp/vault_password.txt"
        mode: '0600'

    - name: Execute profiles playbook
      ansible.builtin.shell:
        cmd: >
          ansible-playbook -v -i "{{ hosts_list | join(',') }}," 
          --vault-password-file=/tmp/vault_password.txt 
          playbook.yml
        chdir: "{{ playbook_dir }}/profiles"
      register: playbook_output
      ignore_errors: yes

    - name: Показать вывод дочернего плейбука
      ansible.builtin.debug:
        var: playbook_output.stdout_lines

    - name: Выполнить плейбук setup_keys.yml
      ansible.builtin.command:
        cmd: >
          ansible-playbook -v -i "{{ hosts_list | join(',') }}," 
          --vault-password-file=/tmp/vault_password.txt 
          "{{ playbook_dir }}/wireguard/setup_keys.yml"
        chdir: "{{ playbook_dir }}/wireguard"
      register: setup_keys_output
      ignore_errors: yes

    - name: Показать вывод дочернего плейбука setup_keys.yml
      ansible.builtin.debug:
        var: setup_keys_output.stdout_lines

    - name: Удалить временный файл с паролем
      ansible.builtin.file:
        path: "/tmp/vault_password.txt"
        state: absent