- name: Управление профилями
  hosts: all
  vars_files:
    - const.yml
  tasks:
    - name: Создать профили
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        state: present
      loop: "{{ profiles }}"

    - name: Создать группы
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      loop: "{{ profiles }}"