- name: Настройка сети узла aa
  hosts: network_nodes
  become: yes
  gather_facts: yes  # Включаем сбор фактов для получения MAC-адреса
  tasks:
    - name: Получение MAC-адреса интерфейса ens128
      set_fact:
        mac_address: "{{ ansible_facts['interfaces']['ens128']['macaddress'] }}"

    - name: Настройка IPv6 для продакшн (CD)
      lineinfile:
        path: /etc/network/interfaces.d/ens128.cfg
        line: |
          auto ens128
          iface ens128 inet6 static
              address fdba::
              netmask 16
        create: yes

    - name: Добавление маршрутов IPv6
      command: "ip -6 route add {{ item }} dev ens128"
      with_items:
        - "fdbb::/16"
        - "fcbb::/16"
      ignore_errors: yes

    - name: Настройка NDP (таблица соседей)
      command: "ip -6 neigh add {{ item.ip }} lladdr {{ mac_address }} dev ens128 nud permanent"
      with_items:
        - { ip: "fdbb::" }
        - { ip: "fcbb::" }
      ignore_errors: yes

    - name: Перезапуск сети
      command: systemctl restart networking
          
    - name: Проверка IPv6 адресов
      shell: "ip -6 addr show dev ens128"
      register: ipv6_addr
      changed_when: false

    - name: Вывод IPv6 адресов
      debug:
        var: ipv6_addr.stdout

    - name: Проверка IPv6 маршрутов
      shell: "ip -6 route show"
      register: ipv6_route
      changed_when: false

    - name: Вывод IPv6 маршрутов
      debug:
        var: ipv6_route.stdout

    - name: Проверка пинга IPv4
      shell: "ping -c 1 10.10"
      register: ping_ipv4
      changed_when: false

    - name: Вывод результатов пинга IPv4
      debug:
        var: ping_ipv4.stdout

- name: Настройка сети
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Установка имени хоста
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Определение интерфейса
      set_fact:
        network_interface: "{{ ansible_default_ipv4.interface }}"

    - name: Настройка IPv6 адреса
      lineinfile:
        path: "/etc/network/interfaces.d/{{ network_interface }}.cfg"
        line: |
          auto {{ network_interface }}
          iface {{ network_interface }} inet6 static
              address {{ 'fdba::' if inventory_hostname == 'aa' else 'fcba::' }}
              netmask 16
        create: yes

    - name: Настройка маршрутов для IPv6
      shell: |
        sudo ip -6 route add {{ 'fdbb::/16' if inventory_hostname == 'aa' else 'fcbb::/16' }} dev {{ network_interface }}

    - name: Перезапуск сети для применения изменений
      command: systemctl restart networking
